# Generated by Django 3.1 on 2020-11-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('PetName', models.CharField(max_length=255)),
                ('Breed', models.CharField(max_length=255)),
            ],
        ),
    ]
